app/admins/urls.py
from django.urls import path
from .views import RegisterAdminView,ConfirmAdminListView,AcceptAdminView,DeclineAdminView
app_name = "admins"

urlpatterns = [
    path("register-admin/",RegisterAdminView.as_view(),name="register-admin"),
    path("confirm-admin-list/",ConfirmAdminListView.as_view(),name="confrim-admin-list"),
    path("accept-admin/<str:email>/",AcceptAdminView.as_view(),name="accept-admin"),
    path("decline-admin/<str:email>/",DeclineAdminView.as_view(),name="decline-admin"),
]

app/base/urls.py
from django.urls import path
from .views import (homePage, ProfileView,)

app_name = "base"

urlpatterns = [
    path("",homePage,name="home"),
    path("profile/<int:id>/<str:email>/",ProfileView.as_view(),name="profile"),


]

app/doctor/urls.py
from django.urls import path
from .views import (RegisterDoctorView, ConfirmDoctorListView, AcceptDoctorView, DeclineDoctorView,
                    SendMessage, UnreadMessageList,
                    MessageDetail,AllMessageList,ReadMessageStatus,CloseMessageStatus)
app_name = "doctor"
urlpatterns = [
    path("register-doctor/",RegisterDoctorView.as_view(),name="register-doctor"),

    path("confirm-doctor-page/",ConfirmDoctorListView.as_view(),name="confirm-doctor-page"),
    path("accept-doctor/<str:email>/",AcceptDoctorView.as_view(),name="accept-doctor"),
    path("decline-doctor/<str:email>/",DeclineDoctorView.as_view(),name="decline-doctor"),

    path("send-message/",SendMessage.as_view(),name='send-message'),
    path("unread-messages-list/",UnreadMessageList.as_view(),name="unread-messages"),
    path("all-message-list/",AllMessageList.as_view(),name="all-messages"),

    path("message-detail/<str:token>/",MessageDetail.as_view(),name="message-detail"),
    path("message-read/<str:token>/",ReadMessageStatus.as_view(),name="read-message"),
    path("message-close/<str:token>/",CloseMessageStatus.as_view(),name="close-message"),

]

app/hospital/urls.py
from django.urls import path
from hospital.views import (RegisterHospitalView, ConfirmHospitalListView,
                            HospitalProfileView, AcceptHospitalView, DeclineHospitalView,)

app_name = "hospital"

urlpatterns = [
    path("register-hospital/",RegisterHospitalView.as_view(),name="register-hospital"),
    path("hospital-confirm-list/",ConfirmHospitalListView.as_view(),name="hospital-confirm-list"),
    path("profile/<str:id>/",HospitalProfileView.as_view(),name="profile"),
    path("accept-hospital/<int:id>/<int:hospital_id>/",AcceptHospitalView.as_view(),name="accept-hospital"),
    path("decline-hospital/<int:id>/<int:hospital_id>/",DeclineHospitalView.as_view(),name="decline-hospital"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superuser/', admin.site.urls),
    path("accounts/", include("allauth.urls")),

    path("",include("app.base.urls")),
    path("hospital/",include("app.hospital.urls")),
    path("doctor/",include("app.doctor.urls")),
    path("admin/",include("app.admins.urls")),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


handler404 = 'app.base.views.page_not_found'
handler500 = 'app.base.views.server_error'

app/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from hospital.models import Hospital
import random
# Create your models here.

class UserManager(BaseUserManager):
    '''
        Manager for creating user
    '''
    def create_user(self, email, first_name, last_name, picture, birthday, user_id, description, user_status, password):
        '''
            Create a user
        '''
        if not email:
            raise ValueError("Email is required")

        user = self.model(email= email,
                          first_name= first_name, last_name= last_name, picture=picture,
                          birthday= birthday, user_id=user_id, description=description,
                          token= random.randint(1, 99999999999999), user_status= "admin"
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, user_id, password):
        # create new superuser
        user = self.model(email=email,
                          user_status="su",
                          first_name=first_name, last_name=last_name,
                          user_id=user_id, description="This user is root",
                          token=random.randint(1, 99999999999999)
                          )

        user.set_password(password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class BaseUser(AbstractUser):
    # base info
    class status(models.TextChoices):
        patient = ("pa","patient")
        superuser = ("su","superuser")
        admin = ("ad","admin")
        doctor = ("do","doctor")

    picture = models.ImageField(blank=True,null=True, upload_to="user-profiles/")
    email = models.EmailField(unique=True)
    username = None
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    description = models.TextField(blank=True,null=True)
    birthday = models.DateField(blank=True,null=True)
    user_id = models.PositiveIntegerField(unique=True,blank=True,null=True)
    token = models.CharField(max_length=15,null=True,blank=True,unique=True)
    user_status = models.CharField(max_length=2,choices=status.choices, default=status.patient,blank=True,null=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "user_id"]

    def __str__(self):
        return self.email

app/base/forms.py
from django import forms
from  django.contrib.auth.forms import UserCreationForm
from base.models import BaseUser

import random

class RegisterUserForm(UserCreationForm):
    token = forms.CharField(widget = forms.HiddenInput(), required = False)

    class Meta:
        model = BaseUser
        fields = ('first_name','last_name','email','picture','birthday','description','user_id', "token")

        help_texts = {
            'first_name': "Enter your first name",
            'last_name' : "Enter your last name",
            "birthday" : "Enter your date of birth format yyyy-mm-dd",
            "description" : "Enter extra notes such as disease ",
            "user_id" : "Enter your id",
        }

    def save(self, commit=True):
        # generate a custom token
        user = super(RegisterUserForm, self).save(commit=False)
        user.token = random.randint(1, 99999999999999)
        if commit:
            user.save()

        return user

app/base/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid

from base.models import BaseUser
from doctor.models import Doctor
from admins.models import Admin
# Create your views here.


def homePage(request):
    return  render(request,"base-app/home.html")


class ProfileView(LoginRequiredMixin,DetailView):
    template_name = "base-app/profile.html"
    context_object_name = "user"

    def get_object(self, *args, **kwargs):
        object = get_object_or_404(BaseUser, id= self.kwargs["id"], email=self.kwargs['email'])
        return object

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        user = BaseUser.objects.filter(email= self.kwargs["email"], pk= self.kwargs["id"]).first()
        context['doctor_request'] = user.applier.filter(doctor_status = "re")
        context['admin_request'] = user.admin_applier.filter(admin_stat= "re")
        return context

def page_not_found(request, exception):
    return render(request, "base-app/404.html", {})

def server_error(request, exception=None):
    return render(request, "base-app/500.html", {})

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%load static%}
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/35fb6f5eb9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'base/style.css' %}">
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
{%include 'base/navbar.html'%}
{% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
{% endif %}
<div class="main-box">
    {%block body%}
    {%endblock%}
</div>
{%include 'base/footer.html'%}
</body>
</html>

templates/base/footer.html
<footer class="text-center text-lg-start bg-light text-muted">
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>

    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="https://github.com/Ml06py/hospital-management" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </section>

  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company
          </h6>
          <p>
            Hospital managemet is here for you to help doctors to keep in touch with other doctors and share patients info with them
          </p>
        </div>
        {%if request.user.is_authenticated%}
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Pages
            </h6>
          {%if request.user.admin_stat == "ac" %}
            <p>
              <a href="{%url 'hospital:register-hospital'%}" class="text-reset">Register hospital</a>
            </p>
          {%endif%}


            {%if request.user.doc_stat != "ac" and "re" and request.user.admin_stat != "ac" and "re"%}
              <p>
                <a href="{%url 'admins:register-admin'%}" class="text-reset">Register Admin</a>
              </p>
              <p>
                <a href="{%url 'doctor:register-doctor'%}" class="text-reset">Register doctor</a>
              </p>
            {%endif%}




          </div>
        {%endif%}
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> New York, Pi 20050, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            management@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 000 000 00</p>
        </div>
      </div>
    </div>
  </section>

  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="#">hospitalManagement.com</a>
  </div>
</footer>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <a class="navbar-brand" style="margin-left:10px;" href="#"><i class="fa-solid fa-hospital"></i></a>
      <li class="nav-item active">
        <a class="nav-link " href="{%url 'base:home'%}">Home  </a>
      </li>
      {%if request.user.is_authenticated%}
      {% if not request.user.is_superuser %}
        {% if request.user.user_status != "do" and request.user.user_status != "ad" %}
          {% if request.user.admin_applier.count == 0 and request.user.applier.count == 0 %}
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Register
              </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{%url 'admins:register-admin'%}">Register Admin</a></li>
                      <li><a class="dropdown-item" href="{%url 'doctor:register-doctor'%}">Register Doctor</a></li>
                    {%if request.user.hospital_owner.count == 0 %}
                      <li><a class="dropdown-item" href="{%url 'hospital:register-hospital' %}">Register Hospital</a></li>
                    {%endif%}
                </ul>
              </div>
      {%endif%}
     {%endif%}
      {% endif %}
      {% if request.user.is_superuser or request.user.user_status == "ad" %}
        <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Pages
              </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{%url 'doctor:confirm-doctor-page'%}">Doctor requests</a></li>
                      <li><a class="dropdown-item" href="{%url 'admins:confrim-admin-list'%}">Admin requests</a></li>
                      <li><a class="dropdown-item" href="{%url 'hospital:hospital-confirm-list'%}">Hospital requests</a></li>

                        {%if request.user.hospital_owner.count == 0 %}
                          <li><a class="dropdown-item" href="{%url 'hospital:register-hospital' %}">Register Hospital</a></li>
                        {%endif%}
                </ul>
              </div>
      {% endif %}
      {%if request.user.applier.first.doctor_status == "ac"%}
        <div class="dropdown">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Messages
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{%url 'doctor:unread-messages' %}">Unread Messages</a></li>
                <li><a class="dropdown-item" href="{%url 'doctor:all-messages' %}">All Messages</a></li>
                <li><a class="dropdown-item" href="{%url 'doctor:send-message' %}">Send Message</a></li>

          </ul>
        </div>
      {%endif%}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'base:profile' request.user.id request.user.email %}">Profile</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'account_logout' %}">Logout</a>
          </li>
      {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_signup' %}">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'account_login' %}">login</a>
          </li>
      {%endif%}
    </ul>
  </div>
</nav>