app/hospital/urls.py
from django.urls import path
from hospital.views import (RegisterHospitalView, ConfirmHospitalListView,
                            HospitalProfileView, AcceptHospitalView, DeclineHospitalView,)

app_name = "hospital"

urlpatterns = [
    path("register-hospital/",RegisterHospitalView.as_view(),name="register-hospital"),
    path("hospital-confirm-list/",ConfirmHospitalListView.as_view(),name="hospital-confirm-list"),
    path("profile/<str:id>/",HospitalProfileView.as_view(),name="profile"),
    path("accept-hospital/<int:id>/<int:hospital_id>/",AcceptHospitalView.as_view(),name="accept-hospital"),
    path("decline-hospital/<int:id>/<int:hospital_id>/",DeclineHospitalView.as_view(),name="decline-hospital"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superuser/', admin.site.urls),
    path("accounts/", include("allauth.urls")),

    path("",include("app.base.urls")),
    path("hospital/",include("app.hospital.urls")),
    path("doctor/",include("app.doctor.urls")),
    path("admin/",include("app.admins.urls")),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


handler404 = 'app.base.views.page_not_found'
handler500 = 'app.base.views.server_error'

app/hospital/models.py
from django.db import models
# Create your models here.

class Hospital(models.Model):
    class status(models.TextChoices):
        accepted = ("a","accepted")
        rejected = ("r","rejected")
        no_answer = ("n","no_answer")
    name = models.CharField(max_length=40)
    address = models.CharField(max_length=80)
    picture = models.ImageField(upload_to="hospital_picture/",null=True,blank=True)
    hospital_id = models.CharField(max_length=20,unique=True)
    phone_number = models.CharField(max_length=12)
    status = models.CharField(max_length=2,choices=status.choices,default=status.no_answer,blank=True,null=True)
    owner = models.ForeignKey(to="base.BaseUser", on_delete=models.CASCADE, blank=True, null=True, related_name="hospital_owner")
    description = models.TextField()
    def __str__(self):
        return self.name

class Message(models.Model):
    title = models.CharField(max_length=30)
    doctor = models.ForeignKey(to="base.BaseUser",related_name="doctor",on_delete=models.CASCADE,blank=True,null=True)
    patient = models.ForeignKey(to="base.BaseUser", on_delete=models.CASCADE, blank=True, null=True)
    to_hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    token = models.CharField(max_length=10,blank=True,null=True)

    class status(models.TextChoices):
        sent = ("s", "sent")
        received = ("r", "received")
        closed = ("c", "closed")
    status = models.CharField(max_length=2,choices=status.choices,default=status.sent,blank=True,null=True)
    def __str__(self):
        return self.title

app/hospital/forms.py
from django import forms
from django.forms import ModelForm
from .models import Hospital

class RegisterHospitalForm(ModelForm):
    class Meta:
        model = Hospital
        fields = ("name","address","picture","hospital_id","phone_number","status","owner","description",)
        help_texts= {
            "name" : "Hospital's name",
            "address": "Hospital's address",
            "picture" : "Hospital's picture",
            "hospital_id" : "Unique hospital id",
            "phone_number":"hospital's phone number",
            "description" : "Tell us about hospital, hospitals owner and ...."
        }

app/hospital/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView ,ListView, DetailView
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Hospital
from base.models import BaseUser
from .forms import RegisterHospitalForm
from .mixins import ConfirmHospitalMixin, HospitalViewMixin
# Create your views here.

class RegisterHospitalView(LoginRequiredMixin, HospitalViewMixin,FormView):
    '''Register a Hospital'''
    form_class = RegisterHospitalForm
    template_name = "hospital/Register_hospital.html"
    @transaction.atomic
    def form_valid(self, form):
        hospital = self.form_class(self.request.POST, self.request.FILES)
        hospital = hospital.save(commit=False)
        hospital.owner = self.request.user
        hospital.status = "n"
        hospital.save()
        messages.success(self.request,"request has been sent, please wait for results.")
        return redirect("base:home")

    def form_invalid(self, form):
        print(form.errors)
        messages.success(self.request, "sth went wrong, please try again later")
        return redirect("base:home")




class ConfirmHospitalListView(LoginRequiredMixin,ConfirmHospitalMixin, ListView):
    '''List of hospital requests'''
    template_name = "hospital/ConfirmHospital.html"
    def get_queryset(self):
        object = Hospital.objects.filter(status="n")
        return object


class HospitalProfileView(LoginRequiredMixin,DetailView):
    '''Hospital profile page'''
    template_name = "hospital/HospitalProfile.html"
    def get_object(self, *args, **kwargs):
        object = get_object_or_404(Hospital,hospital_id=self.kwargs['id'])
        return object


class AcceptHospitalView(LoginRequiredMixin,ConfirmHospitalMixin,DetailView):
    def get(self,request, *args, **kwargs):
        id = self.kwargs['id']
        hospital_id = self.kwargs["hospital_id"]

        hospital = get_object_or_404(Hospital, id= id, hospital_id=hospital_id)

        hospital.status = "a"
        hospital.save()
        return redirect("hospital:hospital-confirm-list")

class DeclineHospitalView(LoginRequiredMixin,ConfirmHospitalMixin,DetailView):
    def get(self, request, *args, **kwargs):
        id = self.kwargs['id']
        hospital_id = self.kwargs["hospital_id"]

        hospital = get_object_or_404(Hospital, id= id, hospital_id=hospital_id)

        hospital.status = "r"
        hospital.save()
        return redirect("hospital:hospital-confirm-list")

templates/hospital/ConfirmHospital.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Confirm Hospital{%endblock%}
</head>
<body>
{%block body%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">address</th>
      <th scope="col">Profile</th>
      <th scope="col">Page</th>
    </tr>
  </thead>
  {%for hospital in object_list%}
    <tbody>
      <tr>
        <td>{{hospital.name}}</td>
        <td>{{hospital.address}}</td>
        <td><img src="{{hospital.picture.url}}" style="width:30px;"></td>
        <td><a href="{%url 'hospital:profile' hospital.hospital_id%}"> <input type="submit" value="Profile" class="btn-green"></a> </td>
      </tr>
    </tbody>
    {% empty %}
      <h3>There is no hospital request</h3>
    {%endfor%}
  </table>
{%endblock%}
</body>
</html>

templates/hospital/HospitalProfile.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Hospital Profile{%endblock%}
</head>
<body>
{%block body%}
{% if object.picture %}
    <img src="{{object.picture.url}}" style="width:50px; border-radius: 50%;"><br><br>
{% endif %}

<h5>Name: {{object.name}}</h5><br>
<h5>Address: {{object.address}}</h5><br>
<h5>Id: {{object.hospital_id}}</h5><br>
<h5>Phone number: {{object.phone_number}}</h5><br>
<h5>Status: {{object.status}}</h5><br>
<h5>owner: {{object.owner}}</h5> <br>
<h5>about: {{object.description}}</h5> <br>
<hr>
{%if request.user.user_status == "ad" or request.user.is_superuser%}
    {%if object.status == "n"%}
        <h4>The owner of hospital ( {{object.owner.email}} ) has requested to register this hospital</h4> <br>
        <a href="{%url 'hospital:accept-hospital' object.pk object.hospital_id %}"><input class="btn-green" value="Accept" ></a>
        <a href="{%url 'hospital:decline-hospital' object.pk object.hospital_id  %}"><input class="btn-red" value="Decline" style=""></a>
    {%endif%}
{%endif%}
{%endblock%}
</body>
</html>

templates/hospital/Register_hospital.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Register Hospital{%endblock%}
</head>
<body>
{%block body%}
<h1>fill out the form below</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.name|as_crispy_field}}<br>
    {{form.address|as_crispy_field}}<br>
    <br><h6>Hospitals picture:</h6>
    {{form.picture}}<br><br>
    {{form.hospital_id|as_crispy_field}}<br>
    {{form.description|as_crispy_field}}<br>
    {{form.phone_number|as_crispy_field}}<br>
    <input type="submit" value="Save" class="btn-green">
</form>
{%endblock%}
</body>
</html>