app/base/urls.py
from django.urls import path
from .views import (homePage, ProfileView,)

app_name = "base"

urlpatterns = [
    path("",homePage,name="home"),
    path("profile/<int:id>/<str:email>/",ProfileView.as_view(),name="profile"),


]

app/doctor/urls.py
from django.urls import path
from .views import (RegisterDoctorView, ConfirmDoctorListView, AcceptDoctorView, DeclineDoctorView,
                    SendMessage, UnreadMessageList,
                    MessageDetail,AllMessageList,ReadMessageStatus,CloseMessageStatus)
app_name = "doctor"
urlpatterns = [
    path("register-doctor/",RegisterDoctorView.as_view(),name="register-doctor"),

    path("confirm-doctor-page/",ConfirmDoctorListView.as_view(),name="confirm-doctor-page"),
    path("accept-doctor/<str:email>/",AcceptDoctorView.as_view(),name="accept-doctor"),
    path("decline-doctor/<str:email>/",DeclineDoctorView.as_view(),name="decline-doctor"),

    path("send-message/",SendMessage.as_view(),name='send-message'),
    path("unread-messages-list/",UnreadMessageList.as_view(),name="unread-messages"),
    path("all-message-list/",AllMessageList.as_view(),name="all-messages"),

    path("message-detail/<str:token>/",MessageDetail.as_view(),name="message-detail"),
    path("message-read/<str:token>/",ReadMessageStatus.as_view(),name="read-message"),
    path("message-close/<str:token>/",CloseMessageStatus.as_view(),name="close-message"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superuser/', admin.site.urls),
    path("accounts/", include("allauth.urls")),

    path("",include("app.base.urls")),
    path("hospital/",include("app.hospital.urls")),
    path("doctor/",include("app.doctor.urls")),
    path("admin/",include("app.admins.urls")),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


handler404 = 'app.base.views.page_not_found'
handler500 = 'app.base.views.server_error'

app/doctor/models.py
from django.db import models
from hospital.models import Hospital
from base.models import BaseUser
# Create your models here.
class Doctor(models.Model):
    class doctor_status(models.TextChoices):
        requested = ("re", "requested")
        didnt_requested = ("dr", "didnt_requested")
        accepted = ("ac", "accepted")
        declined = ("de", "declined")
        
    applier = models.ForeignKey(BaseUser,on_delete=models.CASCADE,blank=True, related_name="applier")
    doctor_id = models.PositiveIntegerField(blank=True,unique=True,null=True)
    hospital_to_request = models.ForeignKey(Hospital,blank=True, null=True, on_delete=models.CASCADE)
    more_info = models.TextField(blank=True,null=True)
    doctor_status = models.CharField(max_length=2, choices=doctor_status.choices, default=doctor_status.didnt_requested,blank=True,null=True)
    def __str__(self) :
        return self.applier.email

app/doctor/forms.py
from django import forms
from django.forms import ModelForm
from doctor.models import Doctor
from hospital.models import Message

class RegisterDoctorForm(ModelForm):
    class Meta:
        model = Doctor
        fields = ("applier","doctor_id","hospital_to_request","more_info","doctor_status")


class MessageForm(ModelForm):
    hospital_id = forms.CharField()
    patient_id = forms.CharField()
    class Meta:
        model = Message
        fields = ("title","doctor","patient","to_hospital","description","token")

app/doctor/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import FormView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import transaction

import uuid

from base.models import BaseUser
from doctor.models import Doctor
from hospital.models import Hospital, Message
from .forms import RegisterDoctorForm, MessageForm
from .mixins import RegisterDoctorMixin, ConfirmDoctorMixin, ConfirmDoctorPageMixin, MessageMixin

# Create your views here.
class RegisterDoctorView(LoginRequiredMixin,RegisterDoctorMixin,FormView):
    '''Register a doctor'''
    form_class = RegisterDoctorForm
    template_name = "doctor/RegisterDoctor.html"
    @transaction.atomic
    def form_valid(self, form):
        hospital_token = self.request.POST["hospital_token"]
        hospital = Hospital.objects.filter(hospital_id=hospital_token).first()

        form = form.save(commit=False)
        form.applier = self.request.user
        form.hospital_to_request = hospital
        form.doctor_status = "re"

        form.save()
        messages.success(self.request, "request has been sent, please wait for results.")
        return redirect("base:home")
    def form_invalid(self, form):
        messages.success(self.request, "sth went wrong please try again later")
        return redirect("base:home")


class ConfirmDoctorListView(LoginRequiredMixin,ConfirmDoctorPageMixin, ListView):
    '''List of doctor requests'''
    template_name = "doctor/ConfirmDoctor.html"
    def get_queryset(self):
        object = Doctor.objects.filter(doctor_status="re")
        return object

class AcceptDoctorView(LoginRequiredMixin,ConfirmDoctorMixin,DetailView):
    '''Accept a doctor request'''
    def get(self,request, *args, **kwargs):
        doctor = get_object_or_404(Doctor, applier__email=self.kwargs['email'])
        user = get_object_or_404(BaseUser, email=self.kwargs['email'])

        doctor.doctor_status = "ac"
        user.user_status = "do"

        doctor.save()
        user.save()
        return redirect("doctor:confirm-doctor-page")

class DeclineDoctorView(LoginRequiredMixin,ConfirmDoctorMixin,DetailView):
    '''Decline a doctor request'''
    def get(self,request,username, *args, **kwargs):
        doctor = get_object_or_404(Doctor, applier__email=self.kwargs['email'])
        user = get_object_or_404(BaseUser, email=self.kwargs['email'])

        doctor.doctor_status = "de"
        user.user_status = "pa"

        doctor.save()
        user.save()
        return redirect("doctor:confirm-doctor-page")


class SendMessage(LoginRequiredMixin,MessageMixin,FormView):
    form_class = MessageForm
    template_name = "doctor/AddMessage.html"
    @transaction.atomic()
    def form_valid(self, form):
        patient_id =self.request.POST["patient_id"]
        hospital_id = self.request.POST["hospital_id"]

        patient = BaseUser.objects.filter(user_id=patient_id).first()
        hospital = Hospital.objects.filter(hospital_id=hospital_id).first()

        form = form.save(commit=False)
        form.token = uuid.uuid4().hex.upper()[0:10]
        form.doctor = self.request.user
        form.patient = patient
        form.to_hospital  = hospital
        form.save()
        messages.success(self.request, "message sent.")
        return redirect("base:home")

    def form_invalid(self, form):
        messages.success(self.request, "sth went wrong...")


class UnreadMessageList(LoginRequiredMixin,MessageMixin,ListView):
    template_name = "doctor/MessageList.html"
    def get_queryset(self):
        user = self.request.user.applier.first()
        object = Message.objects.filter(to_hospital=user.hospital_to_request,
                                        status=["s","r"])
        return object

class AllMessageList(LoginRequiredMixin,MessageMixin,ListView):
    template_name = "doctor/MessageList.html"
    def get_queryset(self):
        user = self.request.user.applier.first()
        object = Message.objects.filter(to_hospital= user.hospital_to_request)
        return object

class MessageDetail(LoginRequiredMixin,MessageMixin,DetailView):
    template_name = "doctor/MessageDetail.html"
    def get_object(self,*args,**kwargs):
        return  get_object_or_404(
            Message,
            token = self.kwargs['token']
        )

class ReadMessageStatus(LoginRequiredMixin,MessageMixin,DetailView):
    def get(self,*args, **kwargs):
        token = self.kwargs['token']
        object = Message.objects.filter(token= token)
        object.update(status="r")
        return redirect("doctor:message-detail", token= token)

class CloseMessageStatus(LoginRequiredMixin,MessageMixin,DetailView):
    def get(self,*args, **kwargs):
        object = get_object_or_404(Message, token=self.kwargs['token'])
        object.update(status="c")
        return  redirect("doctor:unread-messages")

templates/doctor/AddMessage.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Add message{%endblock%}
</head>
<body>
{%block body%}
<h1>fill out the form below</h1>

<form method="post">
    {% csrf_token %}
    {{form.title|as_crispy_field}}<br>
    {{form.description|as_crispy_field}}<br>
        <div class="mb-3">
            <label for="hospital_id" class="form-label">hospital id</label>
            <input type="text" class="form-control" name="hospital_id" required>
            <label for="patient_id" class="form-label">patient id</label>
            <input type="text" class="form-control" name="patient_id" required>
        </div>

    <input type="submit" value="Request" class="btn-green">
</form>
{%endblock%}
</body>
</html>

templates/doctor/ConfirmDoctor.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Confirm Doctor{%endblock%}
</head>
<body>
{%block body%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Name</th>
      <th scope="col">Profile</th>
      <th scope="col">Page</th>
    </tr>
  </thead>
  {%for users in object_list %}
      <tbody>
        <tr>
          <td>{{users.applier.email}}</td>
          <td>{{users.get_full_name}}</td>
          {% if users.applier.picture %}
            <td><img src="{{users.applier.picture.url}}" style="width:30px;"></td>
          {% endif %}
          <td><a href="{%url 'base:profile' users.applier.id users.applier.email%}"> <input type="submit" value="Profile" class="btn-green"></a> </td>
        </tr>
      </tbody>
    {% empty %}
      <h3>There is no doctor request</h3>
    {%endfor%}
</table>
{%endblock%}
</body>
</html>

templates/doctor/MessageDetail.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Message detail{%endblock%}
</head>
<body>
{%block body%}
<h5>Title: {{object.title}}</h5><br>
<h5>Description: {{object.description}}</h5><br>
<h5>From: {{object.doctor}}</h5><br>
<h5>To: {{object.to_hospital}}</h5><br>
<h5>Patient: {{object.patient}}</h5><br>
<h5>Status: {{object.status}}</h5><br>
{%if object.status != "r"%}
    <a href="{% url 'doctor:read-message' object.token%}" class="btn-green">Read message</a>
{%elif object.status == "r"%}
    <a href="{% url 'doctor:close-message' object.token%}" class="btn-green">Close message</a>
{%endif%}
{%endblock%}
</body>
</html>

templates/doctor/MessageList.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Messages{%endblock%}
</head>
<body>
{%block body%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">patient</th>
      <th scope="col">status</th>
      <th scope="col">From</th>
    </tr>
  </thead>
  {%for message in object_list%}
  <tbody>
    <tr>
      <td><a href="{%url 'doctor:message-detail' message.token %}">{{message.title}}</a> </td>
      <td>{{message.patient}}</td>
      <td>{{message.status}}</td>
      <td>{{message.doctor}}</td>
    </tr>
  </tbody>
    {%endfor%}
</table>
{%endblock%}
</body>
</html>

templates/doctor/RegisterDoctor.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load crispy_forms_tags %}
    {%block title%}Register Doctor{%endblock%}
</head>
<body>
{%block body%}
<h1>fill out the form below</h1>

<form method="post">
    {% csrf_token %}
    {{form.doctor_id|as_crispy_field}}<br>
    {{form.more_info|as_crispy_field}}<br>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Hospital token</label>
        <input type="text" class="form-control" name="hospital_token" required>
      </div>
      <input type="submit" value="Request" class="btn-green">
</form>
{%endblock%}
</body>
</html>