app/admins/urls.py
from django.urls import path
from .views import RegisterAdminView,ConfirmAdminListView,AcceptAdminView,DeclineAdminView
app_name = "admins"

urlpatterns = [
    path("register-admin/",RegisterAdminView.as_view(),name="register-admin"),
    path("confirm-admin-list/",ConfirmAdminListView.as_view(),name="confrim-admin-list"),
    path("accept-admin/<str:email>/",AcceptAdminView.as_view(),name="accept-admin"),
    path("decline-admin/<str:email>/",DeclineAdminView.as_view(),name="decline-admin"),
]

app/doctor/urls.py
from django.urls import path
from .views import (RegisterDoctorView, ConfirmDoctorListView, AcceptDoctorView, DeclineDoctorView,
                    SendMessage, UnreadMessageList,
                    MessageDetail,AllMessageList,ReadMessageStatus,CloseMessageStatus)
app_name = "doctor"
urlpatterns = [
    path("register-doctor/",RegisterDoctorView.as_view(),name="register-doctor"),

    path("confirm-doctor-page/",ConfirmDoctorListView.as_view(),name="confirm-doctor-page"),
    path("accept-doctor/<str:email>/",AcceptDoctorView.as_view(),name="accept-doctor"),
    path("decline-doctor/<str:email>/",DeclineDoctorView.as_view(),name="decline-doctor"),

    path("send-message/",SendMessage.as_view(),name='send-message'),
    path("unread-messages-list/",UnreadMessageList.as_view(),name="unread-messages"),
    path("all-message-list/",AllMessageList.as_view(),name="all-messages"),

    path("message-detail/<str:token>/",MessageDetail.as_view(),name="message-detail"),
    path("message-read/<str:token>/",ReadMessageStatus.as_view(),name="read-message"),
    path("message-close/<str:token>/",CloseMessageStatus.as_view(),name="close-message"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superuser/', admin.site.urls),
    path("accounts/", include("allauth.urls")),

    path("",include("app.base.urls")),
    path("hospital/",include("app.hospital.urls")),
    path("doctor/",include("app.doctor.urls")),
    path("admin/",include("app.admins.urls")),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


handler404 = 'app.base.views.page_not_found'
handler500 = 'app.base.views.server_error'

templates/base-app/home.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Home{%endblock%}
</head>
<body>
{%block body%}
<h1>Hospital Management</h1>
<p>This website can help doctors to save their time</p>
<p>First of all everyone needs to be registered</p>
<p>We are all patients by default we can be promoted as doctor, admin and also we can register hospitals</p>
<p>Doctors can share patients info by usings their Message option</p>
<p>Doctors can see patients previous problems via their profile</p>
{%endblock%}
</body>
</html>

templates/base-app/profile.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Profile{%endblock%}
</head>
<body>
{%block body%}
<h3>Profile page</h3>
<hr>
{% if user.profile %}
    <img src="{{object.picture.url}}" style="width:50px; border-radius: 50%;"><br><br>
{% endif %}
<h5>Full name: {{user.get_full_name}}</h5><br>
<h5>Email: {{user.email}}</h5><br>
<h5>Birthday: {{user.birthday}}</h5><br>
<h5>Userid: {{user.userid}}</h5><br>
<h5>Description:</h5> <p>{{user.description}}</p><br>
<h5>Current status: {{user.user_status}}</h5><br>
<hr>
{% if request.user.is_superuser or request.user.user_status == "ad" %}
    {% if doctor_request %}
        <h4>This user has requested for promote to doctor level.</h4> <br>
        <a href="{%url 'doctor:accept-doctor' user.email%}"><input class="btn-green" value="Accept" ></a>
        <a href="{%url 'doctor:decline-doctor' user.email%}"><input class="btn-red" value="Decline Doctor" ></a>
    {% endif %}
    {% if admin_request %}
        <h4>This user has requested for promote to admin level</h4> <br>
        <a href="{%url 'admins:accept-admin' object.email   %}"><input class="btn-green" value="Accept" ></a>
        <a href="{%url 'admins:decline-admin' object.email%}"><input class="btn-red" value="Decline Admin" ></a>
    {% endif %}
{% endif %}

{%endblock%}
</body>
</html>